messenger4j:
  appSecret: 4b3543a861d201103cc12b3dd48f446b
  verifyToken : sidhe2005
  pageAccessToken: EAAVVh44bG8cBAJo4adqfLiyVyXl8KnlOWCpPZA7UBkhVJFdrta55ZAYZBfTmfsNmqBiiZAluejw3n7AjH0ZCnZA2NAs1xlCdI5ZALVACsjomIwOmmrQpV28SQG3UaVZAGGMcujHeNm6i7ruixVZBboYH76bBZCxH20ZCiUh6sXdA7rPZBZADmaa0ZBsJE9

logging:
  level:
    com:
      github:
        messenger4j: INFO



spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  # enable H2 web console and set url for web console
  #l http://locahost:8080/console
  h2:
    console:
      enabled: true
      path: /console



